// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: article.proto

package articlesapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Article is the list-shaped view of an article. It deliberately omits the
// body, which is only served by GetArticleDetails.
type Article struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title   *string                `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Summary *string                `protobuf:"bytes,3,opt,name=summary" json:"summary,omitempty"`
	// Path relative to the image CDN's base URL, for example
	// "/articles/technology-01.svg". The host is configuration, not data.
	ImagePath   *string                `protobuf:"bytes,4,opt,name=image_path,json=imagePath" json:"image_path,omitempty"`
	Author      *string                `protobuf:"bytes,5,opt,name=author" json:"author,omitempty"`
	Source      *string                `protobuf:"bytes,6,opt,name=source" json:"source,omitempty"`
	Category    *string                `protobuf:"bytes,7,opt,name=category" json:"category,omitempty"`
	PublishedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=published_at,json=publishedAt" json:"published_at,omitempty"`
	// Disabled articles are not served to users. The flag is applied
	// asynchronously, so it reflects the last state the ingestion service wrote,
	// not necessarily the most recent request.
	Disabled      *bool `protobuf:"varint,9,opt,name=disabled" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *Article) GetImagePath() string {
	if x != nil && x.ImagePath != nil {
		return *x.ImagePath
	}
	return ""
}

func (x *Article) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *Article) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *Article) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *Article) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Article) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

type ArticleDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article" json:"article,omitempty"`
	Body          *string                `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleDetails) Reset() {
	*x = ArticleDetails{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleDetails) ProtoMessage() {}

func (x *ArticleDetails) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleDetails.ProtoReflect.Descriptor instead.
func (*ArticleDetails) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleDetails) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *ArticleDetails) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

var File_article_proto protoreflect.FileDescriptor

const file_article_proto_rawDesc = "" +
	"\n" +
	"\rarticle.proto\x12\x1csliide.services.articles.api\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"image_path\x18\x04 \x01(\tR\timagePath\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12=\n" +
	"\fpublished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x1a\n" +
	"\bdisabled\x18\t \x01(\bR\bdisabled\"e\n" +
	"\x0eArticleDetails\x12?\n" +
	"\aarticle\x18\x01 \x01(\v2%.sliide.services.articles.api.ArticleR\aarticle\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04bodyB>Z<github.com/sliide/articles-core/pkg/articles/api;articlesapib\beditionsp\xe8\a"

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData []byte
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)))
	})
	return file_article_proto_rawDescData
}

var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_article_proto_goTypes = []any{
	(*Article)(nil),               // 0: sliide.services.articles.api.Article
	(*ArticleDetails)(nil),        // 1: sliide.services.articles.api.ArticleDetails
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_article_proto_depIdxs = []int32{
	2, // 0: sliide.services.articles.api.Article.published_at:type_name -> google.protobuf.Timestamp
	0, // 1: sliide.services.articles.api.ArticleDetails.article:type_name -> sliide.services.articles.api.Article
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
